import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#000",
    paddingTop: 50,
  },
  scrollView: {
    flex: 1,
  },
  tabBar: {
    flexDirection: "row",
    justifyContent: "space-around",
    padding: 10,
    backgroundColor: "transparent",
    alignItems: "center",
  },
  logoItem: {
    padding: 5,
  },
  logoCircle: {
    width: 24,
    height: 24,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#fff",
    justifyContent: "center",
    alignItems: "center",
    overflow: "hidden",
  },
  logoImage: {
    width: 20,
    height: 20,
  },
  tabItem: {
    paddingVertical: 8,
    paddingHorizontal: 16,
    backgroundColor: "#333",
    borderRadius: 20,
    alignItems: "center",
  },
  activeTab: {
    backgroundColor: "#00ff00",
  },
  tabText: {
    fontSize: 14,
    color: "#fff",
    fontFamily: "System",
  },
  section: {
    padding: 10,
  },
  sectionTitle: {
    fontSize: 24,
    color: "#fff",
    marginBottom: 10,
    fontWeight: "bold",
  },
  grid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  cardWrapper: {},
  categoryCard: {
    flexDirection: "row",
    alignItems: "center",
    width: "100%",
    backgroundColor: "#2a2a2a",
    padding: 10,
    borderRadius: 5,
  },
  categoryImage: {
    width: 30,
    height: 30,
    marginRight: 10,
  },
  categoryText: {
    fontSize: 16,
    color: "#fff",
    flex: 1,
    fontFamily: "System",
  },
  recentCard: {
    width: "100%",
    backgroundColor: "#1a1a2a",
    borderRadius: 10,
    padding: 5,
  },
  recentImage: {
    width: "100%",
    height: 110,
    borderRadius: 8,
  },
  audioCard: {
    width: "100%",
    backgroundColor: "#2a2a2a",
    borderWidth: 1,
    borderColor: "#fff",
    borderRadius: 15,
    padding: 10,
  },
  audioImage: {
    width: "100%",
    height: 160,
    borderRadius: 12,
  },
  audioContent: {
    paddingTop: 8,
    alignItems: "center",
  },
  buttonContainer: {
    flexDirection: "row",
    justifyContent: "flex-end",
    marginBottom: 5,
  },
  favoriteButton: {
    padding: 6,
    backgroundColor: "rgba(255, 255, 255, 0.2)",
    borderRadius: 12,
    marginLeft: 5,
  },
  favoriteIcon: {
    width: 18,
    height: 18,
  },
  premiumText: {
    fontSize: 14,
    color: "#00ff00",
    textAlign: "center",
    backgroundColor: "rgba(0, 200, 0, 0.2)",
    paddingVertical: 4,
    paddingHorizontal: 10,
    borderRadius: 12,
    marginBottom: 8,
    fontFamily: "System",
  },
  audioText: {
    fontSize: 16,
    color: "#fff",
    textAlign: "center",
    marginBottom: 8,
    width: "100%",
    numberOfLines: 1,
    ellipsizeMode: "tail",
    fontWeight: "bold",
  },
  textContainer: {
    padding: 5,
  },
  recentText: {
    fontSize: 12,
    color: "#fff",
    textAlign: "center",
    marginBottom: 3,
    width: "100%",
    numberOfLines: 1,
    ellipsizeMode: "tail",
    fontWeight: "bold",
  },
  subTextContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 3,
  },
  subTextButton: {
    backgroundColor: "#333",
    paddingVertical: 4,
    paddingHorizontal: 8,
    borderRadius: 10,
  },
  subTextWrapper: {
    flex: 1,
    alignItems: "center",
  },
  subText: {
    fontSize: 12,
    color: "#bbb",
    textAlign: "center",
    fontFamily: "System",
  },
  loadingText: {
    fontSize: 16,
    color: "#fff",
    textAlign: "center",
    fontFamily: "System",
  },
});
